version: "3.4"
services:
  notes-site:
    image: nginx:latest
    restart: unless-stopped
    labels:
      # Traefik configuration, Hostname needs to be changed
      - traefik.http.routers.notes-http.rule=Host(`notes.dakantz.at`)
      - traefik.http.routers.notes-http.entrypoints=http
      - traefik.http.routers.notes-http.middlewares=redirect
      - traefik.http.routers.notes-https.rule=Host(`notes.dakantz.at`)
      - traefik.http.routers.notes-https.entrypoints=https
      - traefik.http.routers.notes-https.tls=true
      - traefik.http.routers.notes-https.tls.certresolver=letsencrypt
      - traefik.http.services.notes.loadbalancer.server.port=80
      - traefik.http.middlewares.redirect.redirectscheme.scheme=https
    networks:
      - web
    volumes:
      - ./public:/usr/share/nginx/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
networks:
  web:
    external: true